// Generated by jextract

package org.sandium.core.libs.glfw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VkIndirectCommandsLayoutTokenNVX {
 *     VkIndirectCommandsTokenTypeNVX tokenType;
 *     uint32_t bindingUnit;
 *     uint32_t dynamicCount;
 *     uint32_t divisor;
 * }
 * }
 */
public class VkIndirectCommandsLayoutTokenNVX {

    VkIndirectCommandsLayoutTokenNVX() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        glfw3_h.C_INT.withName("tokenType"),
        glfw3_h.C_INT.withName("bindingUnit"),
        glfw3_h.C_INT.withName("dynamicCount"),
        glfw3_h.C_INT.withName("divisor")
    ).withName("VkIndirectCommandsLayoutTokenNVX");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt tokenType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tokenType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VkIndirectCommandsTokenTypeNVX tokenType
     * }
     */
    public static final OfInt tokenType$layout() {
        return tokenType$LAYOUT;
    }

    private static final long tokenType$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VkIndirectCommandsTokenTypeNVX tokenType
     * }
     */
    public static final long tokenType$offset() {
        return tokenType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VkIndirectCommandsTokenTypeNVX tokenType
     * }
     */
    public static int tokenType(MemorySegment struct) {
        return struct.get(tokenType$LAYOUT, tokenType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VkIndirectCommandsTokenTypeNVX tokenType
     * }
     */
    public static void tokenType(MemorySegment struct, int fieldValue) {
        struct.set(tokenType$LAYOUT, tokenType$OFFSET, fieldValue);
    }

    private static final OfInt bindingUnit$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bindingUnit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t bindingUnit
     * }
     */
    public static final OfInt bindingUnit$layout() {
        return bindingUnit$LAYOUT;
    }

    private static final long bindingUnit$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t bindingUnit
     * }
     */
    public static final long bindingUnit$offset() {
        return bindingUnit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t bindingUnit
     * }
     */
    public static int bindingUnit(MemorySegment struct) {
        return struct.get(bindingUnit$LAYOUT, bindingUnit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t bindingUnit
     * }
     */
    public static void bindingUnit(MemorySegment struct, int fieldValue) {
        struct.set(bindingUnit$LAYOUT, bindingUnit$OFFSET, fieldValue);
    }

    private static final OfInt dynamicCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dynamicCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t dynamicCount
     * }
     */
    public static final OfInt dynamicCount$layout() {
        return dynamicCount$LAYOUT;
    }

    private static final long dynamicCount$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t dynamicCount
     * }
     */
    public static final long dynamicCount$offset() {
        return dynamicCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t dynamicCount
     * }
     */
    public static int dynamicCount(MemorySegment struct) {
        return struct.get(dynamicCount$LAYOUT, dynamicCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t dynamicCount
     * }
     */
    public static void dynamicCount(MemorySegment struct, int fieldValue) {
        struct.set(dynamicCount$LAYOUT, dynamicCount$OFFSET, fieldValue);
    }

    private static final OfInt divisor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("divisor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t divisor
     * }
     */
    public static final OfInt divisor$layout() {
        return divisor$LAYOUT;
    }

    private static final long divisor$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t divisor
     * }
     */
    public static final long divisor$offset() {
        return divisor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t divisor
     * }
     */
    public static int divisor(MemorySegment struct) {
        return struct.get(divisor$LAYOUT, divisor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t divisor
     * }
     */
    public static void divisor(MemorySegment struct, int fieldValue) {
        struct.set(divisor$LAYOUT, divisor$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

