// Generated by jextract

package org.sandium.libs.glfw;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class glfw3_h extends glfw3_h_1 {

    glfw3_h() {
        // Should not be called directly
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_SHADER_BALLOT_EXTENSION_NAME "VK_AMD_shader_ballot"
     * }
     */
    public static MemorySegment VK_AMD_SHADER_BALLOT_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_SHADER_BALLOT_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_shader_ballot");
        }
        return Holder.VK_AMD_SHADER_BALLOT_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_TEXTURE_GATHER_BIAS_LOD_EXTENSION_NAME "VK_AMD_texture_gather_bias_lod"
     * }
     */
    public static MemorySegment VK_AMD_TEXTURE_GATHER_BIAS_LOD_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_TEXTURE_GATHER_BIAS_LOD_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_texture_gather_bias_lod");
        }
        return Holder.VK_AMD_TEXTURE_GATHER_BIAS_LOD_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_SHADER_INFO_EXTENSION_NAME "VK_AMD_shader_info"
     * }
     */
    public static MemorySegment VK_AMD_SHADER_INFO_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_SHADER_INFO_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_shader_info");
        }
        return Holder.VK_AMD_SHADER_INFO_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_SHADER_IMAGE_LOAD_STORE_LOD_EXTENSION_NAME "VK_AMD_shader_image_load_store_lod"
     * }
     */
    public static MemorySegment VK_AMD_SHADER_IMAGE_LOAD_STORE_LOD_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_SHADER_IMAGE_LOAD_STORE_LOD_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_shader_image_load_store_lod");
        }
        return Holder.VK_AMD_SHADER_IMAGE_LOAD_STORE_LOD_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_CORNER_SAMPLED_IMAGE_EXTENSION_NAME "VK_NV_corner_sampled_image"
     * }
     */
    public static MemorySegment VK_NV_CORNER_SAMPLED_IMAGE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_CORNER_SAMPLED_IMAGE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_corner_sampled_image");
        }
        return Holder.VK_NV_CORNER_SAMPLED_IMAGE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_IMG_FORMAT_PVRTC_EXTENSION_NAME "VK_IMG_format_pvrtc"
     * }
     */
    public static MemorySegment VK_IMG_FORMAT_PVRTC_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_IMG_FORMAT_PVRTC_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_IMG_format_pvrtc");
        }
        return Holder.VK_IMG_FORMAT_PVRTC_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_EXTERNAL_MEMORY_CAPABILITIES_EXTENSION_NAME "VK_NV_external_memory_capabilities"
     * }
     */
    public static MemorySegment VK_NV_EXTERNAL_MEMORY_CAPABILITIES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_EXTERNAL_MEMORY_CAPABILITIES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_external_memory_capabilities");
        }
        return Holder.VK_NV_EXTERNAL_MEMORY_CAPABILITIES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_EXTERNAL_MEMORY_EXTENSION_NAME "VK_NV_external_memory"
     * }
     */
    public static MemorySegment VK_NV_EXTERNAL_MEMORY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_EXTERNAL_MEMORY_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_external_memory");
        }
        return Holder.VK_NV_EXTERNAL_MEMORY_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_VALIDATION_FLAGS_EXTENSION_NAME "VK_EXT_validation_flags"
     * }
     */
    public static MemorySegment VK_EXT_VALIDATION_FLAGS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_VALIDATION_FLAGS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_validation_flags");
        }
        return Holder.VK_EXT_VALIDATION_FLAGS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_SUBGROUP_BALLOT_EXTENSION_NAME "VK_EXT_shader_subgroup_ballot"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_SUBGROUP_BALLOT_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_SUBGROUP_BALLOT_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_subgroup_ballot");
        }
        return Holder.VK_EXT_SHADER_SUBGROUP_BALLOT_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_SUBGROUP_VOTE_EXTENSION_NAME "VK_EXT_shader_subgroup_vote"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_SUBGROUP_VOTE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_SUBGROUP_VOTE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_subgroup_vote");
        }
        return Holder.VK_EXT_SHADER_SUBGROUP_VOTE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_TEXTURE_COMPRESSION_ASTC_HDR_EXTENSION_NAME "VK_EXT_texture_compression_astc_hdr"
     * }
     */
    public static MemorySegment VK_EXT_TEXTURE_COMPRESSION_ASTC_HDR_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_TEXTURE_COMPRESSION_ASTC_HDR_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_texture_compression_astc_hdr");
        }
        return Holder.VK_EXT_TEXTURE_COMPRESSION_ASTC_HDR_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_ASTC_DECODE_MODE_EXTENSION_NAME "VK_EXT_astc_decode_mode"
     * }
     */
    public static MemorySegment VK_EXT_ASTC_DECODE_MODE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_ASTC_DECODE_MODE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_astc_decode_mode");
        }
        return Holder.VK_EXT_ASTC_DECODE_MODE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_CONDITIONAL_RENDERING_EXTENSION_NAME "VK_EXT_conditional_rendering"
     * }
     */
    public static MemorySegment VK_EXT_CONDITIONAL_RENDERING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_CONDITIONAL_RENDERING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_conditional_rendering");
        }
        return Holder.VK_EXT_CONDITIONAL_RENDERING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME "VK_NVX_device_generated_commands"
     * }
     */
    public static MemorySegment VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NVX_device_generated_commands");
        }
        return Holder.VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_CLIP_SPACE_W_SCALING_EXTENSION_NAME "VK_NV_clip_space_w_scaling"
     * }
     */
    public static MemorySegment VK_NV_CLIP_SPACE_W_SCALING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_CLIP_SPACE_W_SCALING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_clip_space_w_scaling");
        }
        return Holder.VK_NV_CLIP_SPACE_W_SCALING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DIRECT_MODE_DISPLAY_EXTENSION_NAME "VK_EXT_direct_mode_display"
     * }
     */
    public static MemorySegment VK_EXT_DIRECT_MODE_DISPLAY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DIRECT_MODE_DISPLAY_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_direct_mode_display");
        }
        return Holder.VK_EXT_DIRECT_MODE_DISPLAY_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DISPLAY_SURFACE_COUNTER_EXTENSION_NAME "VK_EXT_display_surface_counter"
     * }
     */
    public static MemorySegment VK_EXT_DISPLAY_SURFACE_COUNTER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DISPLAY_SURFACE_COUNTER_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_display_surface_counter");
        }
        return Holder.VK_EXT_DISPLAY_SURFACE_COUNTER_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DISPLAY_CONTROL_EXTENSION_NAME "VK_EXT_display_control"
     * }
     */
    public static MemorySegment VK_EXT_DISPLAY_CONTROL_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DISPLAY_CONTROL_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_display_control");
        }
        return Holder.VK_EXT_DISPLAY_CONTROL_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_GOOGLE_DISPLAY_TIMING_EXTENSION_NAME "VK_GOOGLE_display_timing"
     * }
     */
    public static MemorySegment VK_GOOGLE_DISPLAY_TIMING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_GOOGLE_DISPLAY_TIMING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_GOOGLE_display_timing");
        }
        return Holder.VK_GOOGLE_DISPLAY_TIMING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_SAMPLE_MASK_OVERRIDE_COVERAGE_EXTENSION_NAME "VK_NV_sample_mask_override_coverage"
     * }
     */
    public static MemorySegment VK_NV_SAMPLE_MASK_OVERRIDE_COVERAGE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_SAMPLE_MASK_OVERRIDE_COVERAGE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_sample_mask_override_coverage");
        }
        return Holder.VK_NV_SAMPLE_MASK_OVERRIDE_COVERAGE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_GEOMETRY_SHADER_PASSTHROUGH_EXTENSION_NAME "VK_NV_geometry_shader_passthrough"
     * }
     */
    public static MemorySegment VK_NV_GEOMETRY_SHADER_PASSTHROUGH_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_GEOMETRY_SHADER_PASSTHROUGH_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_geometry_shader_passthrough");
        }
        return Holder.VK_NV_GEOMETRY_SHADER_PASSTHROUGH_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_VIEWPORT_ARRAY2_EXTENSION_NAME "VK_NV_viewport_array2"
     * }
     */
    public static MemorySegment VK_NV_VIEWPORT_ARRAY2_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_VIEWPORT_ARRAY2_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_viewport_array2");
        }
        return Holder.VK_NV_VIEWPORT_ARRAY2_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NVX_MULTIVIEW_PER_VIEW_ATTRIBUTES_EXTENSION_NAME "VK_NVX_multiview_per_view_attributes"
     * }
     */
    public static MemorySegment VK_NVX_MULTIVIEW_PER_VIEW_ATTRIBUTES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NVX_MULTIVIEW_PER_VIEW_ATTRIBUTES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NVX_multiview_per_view_attributes");
        }
        return Holder.VK_NVX_MULTIVIEW_PER_VIEW_ATTRIBUTES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_VIEWPORT_SWIZZLE_EXTENSION_NAME "VK_NV_viewport_swizzle"
     * }
     */
    public static MemorySegment VK_NV_VIEWPORT_SWIZZLE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_VIEWPORT_SWIZZLE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_viewport_swizzle");
        }
        return Holder.VK_NV_VIEWPORT_SWIZZLE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DISCARD_RECTANGLES_EXTENSION_NAME "VK_EXT_discard_rectangles"
     * }
     */
    public static MemorySegment VK_EXT_DISCARD_RECTANGLES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DISCARD_RECTANGLES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_discard_rectangles");
        }
        return Holder.VK_EXT_DISCARD_RECTANGLES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_CONSERVATIVE_RASTERIZATION_EXTENSION_NAME "VK_EXT_conservative_rasterization"
     * }
     */
    public static MemorySegment VK_EXT_CONSERVATIVE_RASTERIZATION_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_CONSERVATIVE_RASTERIZATION_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_conservative_rasterization");
        }
        return Holder.VK_EXT_CONSERVATIVE_RASTERIZATION_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DEPTH_CLIP_ENABLE_EXTENSION_NAME "VK_EXT_depth_clip_enable"
     * }
     */
    public static MemorySegment VK_EXT_DEPTH_CLIP_ENABLE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DEPTH_CLIP_ENABLE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_depth_clip_enable");
        }
        return Holder.VK_EXT_DEPTH_CLIP_ENABLE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SWAPCHAIN_COLOR_SPACE_EXTENSION_NAME "VK_EXT_swapchain_colorspace"
     * }
     */
    public static MemorySegment VK_EXT_SWAPCHAIN_COLOR_SPACE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SWAPCHAIN_COLOR_SPACE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_swapchain_colorspace");
        }
        return Holder.VK_EXT_SWAPCHAIN_COLOR_SPACE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_HDR_METADATA_EXTENSION_NAME "VK_EXT_hdr_metadata"
     * }
     */
    public static MemorySegment VK_EXT_HDR_METADATA_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_HDR_METADATA_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_hdr_metadata");
        }
        return Holder.VK_EXT_HDR_METADATA_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_EXTERNAL_MEMORY_DMA_BUF_EXTENSION_NAME "VK_EXT_external_memory_dma_buf"
     * }
     */
    public static MemorySegment VK_EXT_EXTERNAL_MEMORY_DMA_BUF_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_EXTERNAL_MEMORY_DMA_BUF_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_external_memory_dma_buf");
        }
        return Holder.VK_EXT_EXTERNAL_MEMORY_DMA_BUF_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_QUEUE_FAMILY_FOREIGN_EXTENSION_NAME "VK_EXT_queue_family_foreign"
     * }
     */
    public static MemorySegment VK_EXT_QUEUE_FAMILY_FOREIGN_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_QUEUE_FAMILY_FOREIGN_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_queue_family_foreign");
        }
        return Holder.VK_EXT_QUEUE_FAMILY_FOREIGN_EXTENSION_NAME;
    }
    private static final int VK_QUEUE_FAMILY_FOREIGN_EXT = (int)4294967293L;
    /**
     * {@snippet lang=c :
     * #define VK_QUEUE_FAMILY_FOREIGN_EXT 4294967293
     * }
     */
    public static int VK_QUEUE_FAMILY_FOREIGN_EXT() {
        return VK_QUEUE_FAMILY_FOREIGN_EXT;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DEBUG_UTILS_EXTENSION_NAME "VK_EXT_debug_utils"
     * }
     */
    public static MemorySegment VK_EXT_DEBUG_UTILS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DEBUG_UTILS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_debug_utils");
        }
        return Holder.VK_EXT_DEBUG_UTILS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SAMPLER_FILTER_MINMAX_EXTENSION_NAME "VK_EXT_sampler_filter_minmax"
     * }
     */
    public static MemorySegment VK_EXT_SAMPLER_FILTER_MINMAX_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SAMPLER_FILTER_MINMAX_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_sampler_filter_minmax");
        }
        return Holder.VK_EXT_SAMPLER_FILTER_MINMAX_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_GPU_SHADER_INT16_EXTENSION_NAME "VK_AMD_gpu_shader_int16"
     * }
     */
    public static MemorySegment VK_AMD_GPU_SHADER_INT16_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_GPU_SHADER_INT16_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_gpu_shader_int16");
        }
        return Holder.VK_AMD_GPU_SHADER_INT16_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_MIXED_ATTACHMENT_SAMPLES_EXTENSION_NAME "VK_AMD_mixed_attachment_samples"
     * }
     */
    public static MemorySegment VK_AMD_MIXED_ATTACHMENT_SAMPLES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_MIXED_ATTACHMENT_SAMPLES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_mixed_attachment_samples");
        }
        return Holder.VK_AMD_MIXED_ATTACHMENT_SAMPLES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_SHADER_FRAGMENT_MASK_EXTENSION_NAME "VK_AMD_shader_fragment_mask"
     * }
     */
    public static MemorySegment VK_AMD_SHADER_FRAGMENT_MASK_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_SHADER_FRAGMENT_MASK_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_shader_fragment_mask");
        }
        return Holder.VK_AMD_SHADER_FRAGMENT_MASK_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_INLINE_UNIFORM_BLOCK_EXTENSION_NAME "VK_EXT_inline_uniform_block"
     * }
     */
    public static MemorySegment VK_EXT_INLINE_UNIFORM_BLOCK_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_INLINE_UNIFORM_BLOCK_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_inline_uniform_block");
        }
        return Holder.VK_EXT_INLINE_UNIFORM_BLOCK_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_STENCIL_EXPORT_EXTENSION_NAME "VK_EXT_shader_stencil_export"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_STENCIL_EXPORT_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_STENCIL_EXPORT_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_stencil_export");
        }
        return Holder.VK_EXT_SHADER_STENCIL_EXPORT_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SAMPLE_LOCATIONS_EXTENSION_NAME "VK_EXT_sample_locations"
     * }
     */
    public static MemorySegment VK_EXT_SAMPLE_LOCATIONS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SAMPLE_LOCATIONS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_sample_locations");
        }
        return Holder.VK_EXT_SAMPLE_LOCATIONS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_BLEND_OPERATION_ADVANCED_EXTENSION_NAME "VK_EXT_blend_operation_advanced"
     * }
     */
    public static MemorySegment VK_EXT_BLEND_OPERATION_ADVANCED_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_BLEND_OPERATION_ADVANCED_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_blend_operation_advanced");
        }
        return Holder.VK_EXT_BLEND_OPERATION_ADVANCED_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_FRAGMENT_COVERAGE_TO_COLOR_EXTENSION_NAME "VK_NV_fragment_coverage_to_color"
     * }
     */
    public static MemorySegment VK_NV_FRAGMENT_COVERAGE_TO_COLOR_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_FRAGMENT_COVERAGE_TO_COLOR_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_fragment_coverage_to_color");
        }
        return Holder.VK_NV_FRAGMENT_COVERAGE_TO_COLOR_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_FRAMEBUFFER_MIXED_SAMPLES_EXTENSION_NAME "VK_NV_framebuffer_mixed_samples"
     * }
     */
    public static MemorySegment VK_NV_FRAMEBUFFER_MIXED_SAMPLES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_FRAMEBUFFER_MIXED_SAMPLES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_framebuffer_mixed_samples");
        }
        return Holder.VK_NV_FRAMEBUFFER_MIXED_SAMPLES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_FILL_RECTANGLE_EXTENSION_NAME "VK_NV_fill_rectangle"
     * }
     */
    public static MemorySegment VK_NV_FILL_RECTANGLE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_FILL_RECTANGLE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_fill_rectangle");
        }
        return Holder.VK_NV_FILL_RECTANGLE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_SHADER_SM_BUILTINS_EXTENSION_NAME "VK_NV_shader_sm_builtins"
     * }
     */
    public static MemorySegment VK_NV_SHADER_SM_BUILTINS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_SHADER_SM_BUILTINS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_shader_sm_builtins");
        }
        return Holder.VK_NV_SHADER_SM_BUILTINS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_POST_DEPTH_COVERAGE_EXTENSION_NAME "VK_EXT_post_depth_coverage"
     * }
     */
    public static MemorySegment VK_EXT_POST_DEPTH_COVERAGE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_POST_DEPTH_COVERAGE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_post_depth_coverage");
        }
        return Holder.VK_EXT_POST_DEPTH_COVERAGE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_IMAGE_DRM_FORMAT_MODIFIER_EXTENSION_NAME "VK_EXT_image_drm_format_modifier"
     * }
     */
    public static MemorySegment VK_EXT_IMAGE_DRM_FORMAT_MODIFIER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_IMAGE_DRM_FORMAT_MODIFIER_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_image_drm_format_modifier");
        }
        return Holder.VK_EXT_IMAGE_DRM_FORMAT_MODIFIER_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_VALIDATION_CACHE_EXTENSION_NAME "VK_EXT_validation_cache"
     * }
     */
    public static MemorySegment VK_EXT_VALIDATION_CACHE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_VALIDATION_CACHE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_validation_cache");
        }
        return Holder.VK_EXT_VALIDATION_CACHE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME "VK_EXT_descriptor_indexing"
     * }
     */
    public static MemorySegment VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_descriptor_indexing");
        }
        return Holder.VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_VIEWPORT_INDEX_LAYER_EXTENSION_NAME "VK_EXT_shader_viewport_index_layer"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_VIEWPORT_INDEX_LAYER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_VIEWPORT_INDEX_LAYER_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_viewport_index_layer");
        }
        return Holder.VK_EXT_SHADER_VIEWPORT_INDEX_LAYER_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_SHADING_RATE_IMAGE_EXTENSION_NAME "VK_NV_shading_rate_image"
     * }
     */
    public static MemorySegment VK_NV_SHADING_RATE_IMAGE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_SHADING_RATE_IMAGE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_shading_rate_image");
        }
        return Holder.VK_NV_SHADING_RATE_IMAGE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_RAY_TRACING_EXTENSION_NAME "VK_NV_ray_tracing"
     * }
     */
    public static MemorySegment VK_NV_RAY_TRACING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_RAY_TRACING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_ray_tracing");
        }
        return Holder.VK_NV_RAY_TRACING_EXTENSION_NAME;
    }
    private static final int VK_SHADER_UNUSED_NV = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define VK_SHADER_UNUSED_NV 4294967295
     * }
     */
    public static int VK_SHADER_UNUSED_NV() {
        return VK_SHADER_UNUSED_NV;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_REPRESENTATIVE_FRAGMENT_TEST_EXTENSION_NAME "VK_NV_representative_fragment_test"
     * }
     */
    public static MemorySegment VK_NV_REPRESENTATIVE_FRAGMENT_TEST_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_REPRESENTATIVE_FRAGMENT_TEST_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_representative_fragment_test");
        }
        return Holder.VK_NV_REPRESENTATIVE_FRAGMENT_TEST_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_FILTER_CUBIC_EXTENSION_NAME "VK_EXT_filter_cubic"
     * }
     */
    public static MemorySegment VK_EXT_FILTER_CUBIC_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_FILTER_CUBIC_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_filter_cubic");
        }
        return Holder.VK_EXT_FILTER_CUBIC_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_GLOBAL_PRIORITY_EXTENSION_NAME "VK_EXT_global_priority"
     * }
     */
    public static MemorySegment VK_EXT_GLOBAL_PRIORITY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_GLOBAL_PRIORITY_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_global_priority");
        }
        return Holder.VK_EXT_GLOBAL_PRIORITY_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_EXTERNAL_MEMORY_HOST_EXTENSION_NAME "VK_EXT_external_memory_host"
     * }
     */
    public static MemorySegment VK_EXT_EXTERNAL_MEMORY_HOST_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_EXTERNAL_MEMORY_HOST_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_external_memory_host");
        }
        return Holder.VK_EXT_EXTERNAL_MEMORY_HOST_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_BUFFER_MARKER_EXTENSION_NAME "VK_AMD_buffer_marker"
     * }
     */
    public static MemorySegment VK_AMD_BUFFER_MARKER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_BUFFER_MARKER_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_buffer_marker");
        }
        return Holder.VK_AMD_BUFFER_MARKER_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_PIPELINE_COMPILER_CONTROL_EXTENSION_NAME "VK_AMD_pipeline_compiler_control"
     * }
     */
    public static MemorySegment VK_AMD_PIPELINE_COMPILER_CONTROL_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_PIPELINE_COMPILER_CONTROL_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_pipeline_compiler_control");
        }
        return Holder.VK_AMD_PIPELINE_COMPILER_CONTROL_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_CALIBRATED_TIMESTAMPS_EXTENSION_NAME "VK_EXT_calibrated_timestamps"
     * }
     */
    public static MemorySegment VK_EXT_CALIBRATED_TIMESTAMPS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_CALIBRATED_TIMESTAMPS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_calibrated_timestamps");
        }
        return Holder.VK_EXT_CALIBRATED_TIMESTAMPS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_SHADER_CORE_PROPERTIES_EXTENSION_NAME "VK_AMD_shader_core_properties"
     * }
     */
    public static MemorySegment VK_AMD_SHADER_CORE_PROPERTIES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_SHADER_CORE_PROPERTIES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_shader_core_properties");
        }
        return Holder.VK_AMD_SHADER_CORE_PROPERTIES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_MEMORY_OVERALLOCATION_BEHAVIOR_EXTENSION_NAME "VK_AMD_memory_overallocation_behavior"
     * }
     */
    public static MemorySegment VK_AMD_MEMORY_OVERALLOCATION_BEHAVIOR_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_MEMORY_OVERALLOCATION_BEHAVIOR_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_memory_overallocation_behavior");
        }
        return Holder.VK_AMD_MEMORY_OVERALLOCATION_BEHAVIOR_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_VERTEX_ATTRIBUTE_DIVISOR_EXTENSION_NAME "VK_EXT_vertex_attribute_divisor"
     * }
     */
    public static MemorySegment VK_EXT_VERTEX_ATTRIBUTE_DIVISOR_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_VERTEX_ATTRIBUTE_DIVISOR_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_vertex_attribute_divisor");
        }
        return Holder.VK_EXT_VERTEX_ATTRIBUTE_DIVISOR_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_PIPELINE_CREATION_FEEDBACK_EXTENSION_NAME "VK_EXT_pipeline_creation_feedback"
     * }
     */
    public static MemorySegment VK_EXT_PIPELINE_CREATION_FEEDBACK_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_PIPELINE_CREATION_FEEDBACK_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_pipeline_creation_feedback");
        }
        return Holder.VK_EXT_PIPELINE_CREATION_FEEDBACK_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_SHADER_SUBGROUP_PARTITIONED_EXTENSION_NAME "VK_NV_shader_subgroup_partitioned"
     * }
     */
    public static MemorySegment VK_NV_SHADER_SUBGROUP_PARTITIONED_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_SHADER_SUBGROUP_PARTITIONED_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_shader_subgroup_partitioned");
        }
        return Holder.VK_NV_SHADER_SUBGROUP_PARTITIONED_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_COMPUTE_SHADER_DERIVATIVES_EXTENSION_NAME "VK_NV_compute_shader_derivatives"
     * }
     */
    public static MemorySegment VK_NV_COMPUTE_SHADER_DERIVATIVES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_COMPUTE_SHADER_DERIVATIVES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_compute_shader_derivatives");
        }
        return Holder.VK_NV_COMPUTE_SHADER_DERIVATIVES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_MESH_SHADER_EXTENSION_NAME "VK_NV_mesh_shader"
     * }
     */
    public static MemorySegment VK_NV_MESH_SHADER_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_MESH_SHADER_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_mesh_shader");
        }
        return Holder.VK_NV_MESH_SHADER_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_FRAGMENT_SHADER_BARYCENTRIC_EXTENSION_NAME "VK_NV_fragment_shader_barycentric"
     * }
     */
    public static MemorySegment VK_NV_FRAGMENT_SHADER_BARYCENTRIC_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_FRAGMENT_SHADER_BARYCENTRIC_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_fragment_shader_barycentric");
        }
        return Holder.VK_NV_FRAGMENT_SHADER_BARYCENTRIC_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_SHADER_IMAGE_FOOTPRINT_EXTENSION_NAME "VK_NV_shader_image_footprint"
     * }
     */
    public static MemorySegment VK_NV_SHADER_IMAGE_FOOTPRINT_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_SHADER_IMAGE_FOOTPRINT_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_shader_image_footprint");
        }
        return Holder.VK_NV_SHADER_IMAGE_FOOTPRINT_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_SCISSOR_EXCLUSIVE_EXTENSION_NAME "VK_NV_scissor_exclusive"
     * }
     */
    public static MemorySegment VK_NV_SCISSOR_EXCLUSIVE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_SCISSOR_EXCLUSIVE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_scissor_exclusive");
        }
        return Holder.VK_NV_SCISSOR_EXCLUSIVE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_DEVICE_DIAGNOSTIC_CHECKPOINTS_EXTENSION_NAME "VK_NV_device_diagnostic_checkpoints"
     * }
     */
    public static MemorySegment VK_NV_DEVICE_DIAGNOSTIC_CHECKPOINTS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_DEVICE_DIAGNOSTIC_CHECKPOINTS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_device_diagnostic_checkpoints");
        }
        return Holder.VK_NV_DEVICE_DIAGNOSTIC_CHECKPOINTS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_INTEL_SHADER_INTEGER_FUNCTIONS_2_EXTENSION_NAME "VK_INTEL_shader_integer_functions2"
     * }
     */
    public static MemorySegment VK_INTEL_SHADER_INTEGER_FUNCTIONS_2_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_INTEL_SHADER_INTEGER_FUNCTIONS_2_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_INTEL_shader_integer_functions2");
        }
        return Holder.VK_INTEL_SHADER_INTEGER_FUNCTIONS_2_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_INTEL_PERFORMANCE_QUERY_EXTENSION_NAME "VK_INTEL_performance_query"
     * }
     */
    public static MemorySegment VK_INTEL_PERFORMANCE_QUERY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_INTEL_PERFORMANCE_QUERY_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_INTEL_performance_query");
        }
        return Holder.VK_INTEL_PERFORMANCE_QUERY_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_PCI_BUS_INFO_EXTENSION_NAME "VK_EXT_pci_bus_info"
     * }
     */
    public static MemorySegment VK_EXT_PCI_BUS_INFO_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_PCI_BUS_INFO_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_pci_bus_info");
        }
        return Holder.VK_EXT_PCI_BUS_INFO_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_DISPLAY_NATIVE_HDR_EXTENSION_NAME "VK_AMD_display_native_hdr"
     * }
     */
    public static MemorySegment VK_AMD_DISPLAY_NATIVE_HDR_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_DISPLAY_NATIVE_HDR_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_display_native_hdr");
        }
        return Holder.VK_AMD_DISPLAY_NATIVE_HDR_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME "VK_EXT_fragment_density_map"
     * }
     */
    public static MemorySegment VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_fragment_density_map");
        }
        return Holder.VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SCALAR_BLOCK_LAYOUT_EXTENSION_NAME "VK_EXT_scalar_block_layout"
     * }
     */
    public static MemorySegment VK_EXT_SCALAR_BLOCK_LAYOUT_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SCALAR_BLOCK_LAYOUT_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_scalar_block_layout");
        }
        return Holder.VK_EXT_SCALAR_BLOCK_LAYOUT_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_GOOGLE_HLSL_FUNCTIONALITY1_EXTENSION_NAME "VK_GOOGLE_hlsl_functionality1"
     * }
     */
    public static MemorySegment VK_GOOGLE_HLSL_FUNCTIONALITY1_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_GOOGLE_HLSL_FUNCTIONALITY1_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_GOOGLE_hlsl_functionality1");
        }
        return Holder.VK_GOOGLE_HLSL_FUNCTIONALITY1_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_GOOGLE_DECORATE_STRING_EXTENSION_NAME "VK_GOOGLE_decorate_string"
     * }
     */
    public static MemorySegment VK_GOOGLE_DECORATE_STRING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_GOOGLE_DECORATE_STRING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_GOOGLE_decorate_string");
        }
        return Holder.VK_GOOGLE_DECORATE_STRING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SUBGROUP_SIZE_CONTROL_EXTENSION_NAME "VK_EXT_subgroup_size_control"
     * }
     */
    public static MemorySegment VK_EXT_SUBGROUP_SIZE_CONTROL_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SUBGROUP_SIZE_CONTROL_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_subgroup_size_control");
        }
        return Holder.VK_EXT_SUBGROUP_SIZE_CONTROL_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_SHADER_CORE_PROPERTIES_2_EXTENSION_NAME "VK_AMD_shader_core_properties2"
     * }
     */
    public static MemorySegment VK_AMD_SHADER_CORE_PROPERTIES_2_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_SHADER_CORE_PROPERTIES_2_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_shader_core_properties2");
        }
        return Holder.VK_AMD_SHADER_CORE_PROPERTIES_2_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_AMD_DEVICE_COHERENT_MEMORY_EXTENSION_NAME "VK_AMD_device_coherent_memory"
     * }
     */
    public static MemorySegment VK_AMD_DEVICE_COHERENT_MEMORY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_AMD_DEVICE_COHERENT_MEMORY_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_AMD_device_coherent_memory");
        }
        return Holder.VK_AMD_DEVICE_COHERENT_MEMORY_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_MEMORY_BUDGET_EXTENSION_NAME "VK_EXT_memory_budget"
     * }
     */
    public static MemorySegment VK_EXT_MEMORY_BUDGET_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_MEMORY_BUDGET_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_memory_budget");
        }
        return Holder.VK_EXT_MEMORY_BUDGET_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_MEMORY_PRIORITY_EXTENSION_NAME "VK_EXT_memory_priority"
     * }
     */
    public static MemorySegment VK_EXT_MEMORY_PRIORITY_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_MEMORY_PRIORITY_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_memory_priority");
        }
        return Holder.VK_EXT_MEMORY_PRIORITY_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_DEDICATED_ALLOCATION_IMAGE_ALIASING_EXTENSION_NAME "VK_NV_dedicated_allocation_image_aliasing"
     * }
     */
    public static MemorySegment VK_NV_DEDICATED_ALLOCATION_IMAGE_ALIASING_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_DEDICATED_ALLOCATION_IMAGE_ALIASING_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_dedicated_allocation_image_aliasing");
        }
        return Holder.VK_NV_DEDICATED_ALLOCATION_IMAGE_ALIASING_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME "VK_EXT_buffer_device_address"
     * }
     */
    public static MemorySegment VK_EXT_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_buffer_device_address");
        }
        return Holder.VK_EXT_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_TOOLING_INFO_EXTENSION_NAME "VK_EXT_tooling_info"
     * }
     */
    public static MemorySegment VK_EXT_TOOLING_INFO_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_TOOLING_INFO_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_tooling_info");
        }
        return Holder.VK_EXT_TOOLING_INFO_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SEPARATE_STENCIL_USAGE_EXTENSION_NAME "VK_EXT_separate_stencil_usage"
     * }
     */
    public static MemorySegment VK_EXT_SEPARATE_STENCIL_USAGE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SEPARATE_STENCIL_USAGE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_separate_stencil_usage");
        }
        return Holder.VK_EXT_SEPARATE_STENCIL_USAGE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_VALIDATION_FEATURES_EXTENSION_NAME "VK_EXT_validation_features"
     * }
     */
    public static MemorySegment VK_EXT_VALIDATION_FEATURES_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_VALIDATION_FEATURES_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_validation_features");
        }
        return Holder.VK_EXT_VALIDATION_FEATURES_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_COOPERATIVE_MATRIX_EXTENSION_NAME "VK_NV_cooperative_matrix"
     * }
     */
    public static MemorySegment VK_NV_COOPERATIVE_MATRIX_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_COOPERATIVE_MATRIX_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_cooperative_matrix");
        }
        return Holder.VK_NV_COOPERATIVE_MATRIX_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_NV_COVERAGE_REDUCTION_MODE_EXTENSION_NAME "VK_NV_coverage_reduction_mode"
     * }
     */
    public static MemorySegment VK_NV_COVERAGE_REDUCTION_MODE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_NV_COVERAGE_REDUCTION_MODE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_NV_coverage_reduction_mode");
        }
        return Holder.VK_NV_COVERAGE_REDUCTION_MODE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_FRAGMENT_SHADER_INTERLOCK_EXTENSION_NAME "VK_EXT_fragment_shader_interlock"
     * }
     */
    public static MemorySegment VK_EXT_FRAGMENT_SHADER_INTERLOCK_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_FRAGMENT_SHADER_INTERLOCK_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_fragment_shader_interlock");
        }
        return Holder.VK_EXT_FRAGMENT_SHADER_INTERLOCK_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_YCBCR_IMAGE_ARRAYS_EXTENSION_NAME "VK_EXT_ycbcr_image_arrays"
     * }
     */
    public static MemorySegment VK_EXT_YCBCR_IMAGE_ARRAYS_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_YCBCR_IMAGE_ARRAYS_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_ycbcr_image_arrays");
        }
        return Holder.VK_EXT_YCBCR_IMAGE_ARRAYS_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_HEADLESS_SURFACE_EXTENSION_NAME "VK_EXT_headless_surface"
     * }
     */
    public static MemorySegment VK_EXT_HEADLESS_SURFACE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_HEADLESS_SURFACE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_headless_surface");
        }
        return Holder.VK_EXT_HEADLESS_SURFACE_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_LINE_RASTERIZATION_EXTENSION_NAME "VK_EXT_line_rasterization"
     * }
     */
    public static MemorySegment VK_EXT_LINE_RASTERIZATION_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_LINE_RASTERIZATION_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_line_rasterization");
        }
        return Holder.VK_EXT_LINE_RASTERIZATION_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_HOST_QUERY_RESET_EXTENSION_NAME "VK_EXT_host_query_reset"
     * }
     */
    public static MemorySegment VK_EXT_HOST_QUERY_RESET_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_HOST_QUERY_RESET_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_host_query_reset");
        }
        return Holder.VK_EXT_HOST_QUERY_RESET_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_INDEX_TYPE_UINT8_EXTENSION_NAME "VK_EXT_index_type_uint8"
     * }
     */
    public static MemorySegment VK_EXT_INDEX_TYPE_UINT8_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_INDEX_TYPE_UINT8_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_index_type_uint8");
        }
        return Holder.VK_EXT_INDEX_TYPE_UINT8_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_SHADER_DEMOTE_TO_HELPER_INVOCATION_EXTENSION_NAME "VK_EXT_shader_demote_to_helper_invocation"
     * }
     */
    public static MemorySegment VK_EXT_SHADER_DEMOTE_TO_HELPER_INVOCATION_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_SHADER_DEMOTE_TO_HELPER_INVOCATION_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_shader_demote_to_helper_invocation");
        }
        return Holder.VK_EXT_SHADER_DEMOTE_TO_HELPER_INVOCATION_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_EXT_TEXEL_BUFFER_ALIGNMENT_EXTENSION_NAME "VK_EXT_texel_buffer_alignment"
     * }
     */
    public static MemorySegment VK_EXT_TEXEL_BUFFER_ALIGNMENT_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_EXT_TEXEL_BUFFER_ALIGNMENT_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_EXT_texel_buffer_alignment");
        }
        return Holder.VK_EXT_TEXEL_BUFFER_ALIGNMENT_EXTENSION_NAME;
    }
    /**
     * {@snippet lang=c :
     * #define VK_GOOGLE_USER_TYPE_EXTENSION_NAME "VK_GOOGLE_user_type"
     * }
     */
    public static MemorySegment VK_GOOGLE_USER_TYPE_EXTENSION_NAME() {
        class Holder {
            static final MemorySegment VK_GOOGLE_USER_TYPE_EXTENSION_NAME
                = glfw3_h.LIBRARY_ARENA.allocateFrom("VK_GOOGLE_user_type");
        }
        return Holder.VK_GOOGLE_USER_TYPE_EXTENSION_NAME;
    }
    private static final int GL_ALL_ATTRIB_BITS = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_ATTRIB_BITS 4294967295
     * }
     */
    public static int GL_ALL_ATTRIB_BITS() {
        return GL_ALL_ATTRIB_BITS;
    }
    private static final int GL_ALL_CLIENT_ATTRIB_BITS = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_CLIENT_ATTRIB_BITS 4294967295
     * }
     */
    public static int GL_ALL_CLIENT_ATTRIB_BITS() {
        return GL_ALL_CLIENT_ATTRIB_BITS;
    }
    private static final int GL_CLIENT_ALL_ATTRIB_BITS = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_CLIENT_ALL_ATTRIB_BITS 4294967295
     * }
     */
    public static int GL_CLIENT_ALL_ATTRIB_BITS() {
        return GL_CLIENT_ALL_ATTRIB_BITS;
    }
    private static final int GL_INVALID_INDEX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_INVALID_INDEX 4294967295
     * }
     */
    public static int GL_INVALID_INDEX() {
        return GL_INVALID_INDEX;
    }
    private static final long GL_TIMEOUT_IGNORED = -1L;
    /**
     * {@snippet lang=c :
     * #define GL_TIMEOUT_IGNORED -1
     * }
     */
    public static long GL_TIMEOUT_IGNORED() {
        return GL_TIMEOUT_IGNORED;
    }
    private static final int GL_ALL_SHADER_BITS = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_SHADER_BITS 4294967295
     * }
     */
    public static int GL_ALL_SHADER_BITS() {
        return GL_ALL_SHADER_BITS;
    }
    private static final int GL_ALL_BARRIER_BITS = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_BARRIER_BITS 4294967295
     * }
     */
    public static int GL_ALL_BARRIER_BITS() {
        return GL_ALL_BARRIER_BITS;
    }
    private static final int GL_ALL_PIXELS_AMD = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_PIXELS_AMD 4294967295
     * }
     */
    public static int GL_ALL_PIXELS_AMD() {
        return GL_ALL_PIXELS_AMD;
    }
    private static final int GL_QUERY_ALL_EVENT_BITS_AMD = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_QUERY_ALL_EVENT_BITS_AMD 4294967295
     * }
     */
    public static int GL_QUERY_ALL_EVENT_BITS_AMD() {
        return GL_QUERY_ALL_EVENT_BITS_AMD;
    }
    private static final int GL_ALL_BARRIER_BITS_EXT = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define GL_ALL_BARRIER_BITS_EXT 4294967295
     * }
     */
    public static int GL_ALL_BARRIER_BITS_EXT() {
        return GL_ALL_BARRIER_BITS_EXT;
    }
    private static final int GL_NEXT_BUFFER_NV = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define GL_NEXT_BUFFER_NV -2
     * }
     */
    public static int GL_NEXT_BUFFER_NV() {
        return GL_NEXT_BUFFER_NV;
    }
    private static final int GL_SKIP_COMPONENTS4_NV = (int)-3L;
    /**
     * {@snippet lang=c :
     * #define GL_SKIP_COMPONENTS4_NV -3
     * }
     */
    public static int GL_SKIP_COMPONENTS4_NV() {
        return GL_SKIP_COMPONENTS4_NV;
    }
    private static final int GL_SKIP_COMPONENTS3_NV = (int)-4L;
    /**
     * {@snippet lang=c :
     * #define GL_SKIP_COMPONENTS3_NV -4
     * }
     */
    public static int GL_SKIP_COMPONENTS3_NV() {
        return GL_SKIP_COMPONENTS3_NV;
    }
    private static final int GL_SKIP_COMPONENTS2_NV = (int)-5L;
    /**
     * {@snippet lang=c :
     * #define GL_SKIP_COMPONENTS2_NV -5
     * }
     */
    public static int GL_SKIP_COMPONENTS2_NV() {
        return GL_SKIP_COMPONENTS2_NV;
    }
    private static final int GL_SKIP_COMPONENTS1_NV = (int)-6L;
    /**
     * {@snippet lang=c :
     * #define GL_SKIP_COMPONENTS1_NV -6
     * }
     */
    public static int GL_SKIP_COMPONENTS1_NV() {
        return GL_SKIP_COMPONENTS1_NV;
    }
    private static final int GL_TEXCOORD4_BIT_PGI = (int)2147483648L;
    /**
     * {@snippet lang=c :
     * #define GL_TEXCOORD4_BIT_PGI 2147483648
     * }
     */
    public static int GL_TEXCOORD4_BIT_PGI() {
        return GL_TEXCOORD4_BIT_PGI;
    }
    private static final int GLFW_HAT_RIGHT_UP = (int)3L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HAT_RIGHT_UP 3
     * }
     */
    public static int GLFW_HAT_RIGHT_UP() {
        return GLFW_HAT_RIGHT_UP;
    }
    private static final int GLFW_HAT_RIGHT_DOWN = (int)6L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HAT_RIGHT_DOWN 6
     * }
     */
    public static int GLFW_HAT_RIGHT_DOWN() {
        return GLFW_HAT_RIGHT_DOWN;
    }
    private static final int GLFW_HAT_LEFT_UP = (int)9L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HAT_LEFT_UP 9
     * }
     */
    public static int GLFW_HAT_LEFT_UP() {
        return GLFW_HAT_LEFT_UP;
    }
    private static final int GLFW_HAT_LEFT_DOWN = (int)12L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HAT_LEFT_DOWN 12
     * }
     */
    public static int GLFW_HAT_LEFT_DOWN() {
        return GLFW_HAT_LEFT_DOWN;
    }
    private static final int GLFW_KEY_UNKNOWN = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define GLFW_KEY_UNKNOWN -1
     * }
     */
    public static int GLFW_KEY_UNKNOWN() {
        return GLFW_KEY_UNKNOWN;
    }
    private static final int GLFW_KEY_LAST = (int)348L;
    /**
     * {@snippet lang=c :
     * #define GLFW_KEY_LAST 348
     * }
     */
    public static int GLFW_KEY_LAST() {
        return GLFW_KEY_LAST;
    }
    private static final int GLFW_MOUSE_BUTTON_LAST = (int)7L;
    /**
     * {@snippet lang=c :
     * #define GLFW_MOUSE_BUTTON_LAST 7
     * }
     */
    public static int GLFW_MOUSE_BUTTON_LAST() {
        return GLFW_MOUSE_BUTTON_LAST;
    }
    private static final int GLFW_MOUSE_BUTTON_LEFT = (int)0L;
    /**
     * {@snippet lang=c :
     * #define GLFW_MOUSE_BUTTON_LEFT 0
     * }
     */
    public static int GLFW_MOUSE_BUTTON_LEFT() {
        return GLFW_MOUSE_BUTTON_LEFT;
    }
    private static final int GLFW_MOUSE_BUTTON_RIGHT = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GLFW_MOUSE_BUTTON_RIGHT 1
     * }
     */
    public static int GLFW_MOUSE_BUTTON_RIGHT() {
        return GLFW_MOUSE_BUTTON_RIGHT;
    }
    private static final int GLFW_MOUSE_BUTTON_MIDDLE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GLFW_MOUSE_BUTTON_MIDDLE 2
     * }
     */
    public static int GLFW_MOUSE_BUTTON_MIDDLE() {
        return GLFW_MOUSE_BUTTON_MIDDLE;
    }
    private static final int GLFW_JOYSTICK_LAST = (int)15L;
    /**
     * {@snippet lang=c :
     * #define GLFW_JOYSTICK_LAST 15
     * }
     */
    public static int GLFW_JOYSTICK_LAST() {
        return GLFW_JOYSTICK_LAST;
    }
    private static final int GLFW_GAMEPAD_BUTTON_LAST = (int)14L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_BUTTON_LAST 14
     * }
     */
    public static int GLFW_GAMEPAD_BUTTON_LAST() {
        return GLFW_GAMEPAD_BUTTON_LAST;
    }
    private static final int GLFW_GAMEPAD_BUTTON_CROSS = (int)0L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_BUTTON_CROSS 0
     * }
     */
    public static int GLFW_GAMEPAD_BUTTON_CROSS() {
        return GLFW_GAMEPAD_BUTTON_CROSS;
    }
    private static final int GLFW_GAMEPAD_BUTTON_CIRCLE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_BUTTON_CIRCLE 1
     * }
     */
    public static int GLFW_GAMEPAD_BUTTON_CIRCLE() {
        return GLFW_GAMEPAD_BUTTON_CIRCLE;
    }
    private static final int GLFW_GAMEPAD_BUTTON_SQUARE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_BUTTON_SQUARE 2
     * }
     */
    public static int GLFW_GAMEPAD_BUTTON_SQUARE() {
        return GLFW_GAMEPAD_BUTTON_SQUARE;
    }
    private static final int GLFW_GAMEPAD_BUTTON_TRIANGLE = (int)3L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_BUTTON_TRIANGLE 3
     * }
     */
    public static int GLFW_GAMEPAD_BUTTON_TRIANGLE() {
        return GLFW_GAMEPAD_BUTTON_TRIANGLE;
    }
    private static final int GLFW_GAMEPAD_AXIS_LAST = (int)5L;
    /**
     * {@snippet lang=c :
     * #define GLFW_GAMEPAD_AXIS_LAST 5
     * }
     */
    public static int GLFW_GAMEPAD_AXIS_LAST() {
        return GLFW_GAMEPAD_AXIS_LAST;
    }
    private static final int GLFW_OPENGL_DEBUG_CONTEXT = (int)139271L;
    /**
     * {@snippet lang=c :
     * #define GLFW_OPENGL_DEBUG_CONTEXT 139271
     * }
     */
    public static int GLFW_OPENGL_DEBUG_CONTEXT() {
        return GLFW_OPENGL_DEBUG_CONTEXT;
    }
    private static final int GLFW_ANY_POSITION = (int)2147483648L;
    /**
     * {@snippet lang=c :
     * #define GLFW_ANY_POSITION 2147483648
     * }
     */
    public static int GLFW_ANY_POSITION() {
        return GLFW_ANY_POSITION;
    }
    private static final int GLFW_HRESIZE_CURSOR = (int)221189L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HRESIZE_CURSOR 221189
     * }
     */
    public static int GLFW_HRESIZE_CURSOR() {
        return GLFW_HRESIZE_CURSOR;
    }
    private static final int GLFW_VRESIZE_CURSOR = (int)221190L;
    /**
     * {@snippet lang=c :
     * #define GLFW_VRESIZE_CURSOR 221190
     * }
     */
    public static int GLFW_VRESIZE_CURSOR() {
        return GLFW_VRESIZE_CURSOR;
    }
    private static final int GLFW_HAND_CURSOR = (int)221188L;
    /**
     * {@snippet lang=c :
     * #define GLFW_HAND_CURSOR 221188
     * }
     */
    public static int GLFW_HAND_CURSOR() {
        return GLFW_HAND_CURSOR;
    }
    private static final int GLFW_DONT_CARE = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define GLFW_DONT_CARE -1
     * }
     */
    public static int GLFW_DONT_CARE() {
        return GLFW_DONT_CARE;
    }
}

